// Global object of variables 
module.exports ={
    header:{
        headerText: 'LTC Header',
     },
    footer:{
        footerText: 'LTC Footer',
     },
    normalLoad: "Normal Load",
    fullLoad: "Full Load",
    page1:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
        cell_0_1: '0,1',
        cell_1_1: '1,1',
        cell_2_1: '2,1',
        cell_3_2: '3,2',
        cell_4_2: '4,2',
        cell_5_1: '5,1',
        cell_6_1: '6,1',
        cell_0_3: '0,3',
        cell_1_3: '1,3',
        cell_2_3: '2,3',
        cell_3_5: '3,5',
        cell_4_5: '4,5',
        cell_5_3: '5,3',
        cell_6_3: '6,3',
    },
    page2:{ },
    page3:{ },
    page4:{ },
    page5:{ },
    page6:{ },
    page7:{ },
    page8:{ 
        cell_1_1: '1,1',
        cell_2_1: '2,1',
        cell_3_1: '3,1',
        cell_4_1: '4,1',
        cell_5_1: '5,1',
        cell_6_1: '6,1',
        cell_7_1: '7,1',
        cell_8_1: '8,1',
    },
    page9:{ },
    page10:{ },
    page11:{ },
    page12:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page13:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page14:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page15:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page16:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page17:{ },
    page18:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page19:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page20:{ },
    page21:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page22:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page23:{ },
    page24:{ },
    page25:{ 
        
    },
    page26:{ },
    page27:{ },
    page28:{ },
    page29:{ },
    page30:{ },
    page31:{ },
    page32:{ },
    page33:{ },
    page34:{ },
    page35:{ },
    page36:{ },
    page37:{ },
    page38:{ },
    page39:{ },
    page40:{ },
    page41:{ },
    page42:{ },
    page43:{ },
    page44:{ },
    page45:{ },
    page46:{ },
    page47:{ },
    page48:{ },
    page49:{ },
    page50:{ },
    page51:{ },
    page52:{ },
    page53:{ },
    page54:{ },
    page55:{ },
    page56:{ },
    page57:{ },
    page58:{ },
    page59:{ },
    page60:{ },
    page61:{ },
    page62:{ },
    page63:{ },
    page64:{ },
    page65:{ },
    page66:{ },
    page67:{ },
}