// Global object of variables 
module.exports ={
    header:{
        image1Url: './images/nokia.png',
        image2Url: './images/we.png',
        headerText: 'LTC Header',
     },
    footer:{
        footerText: 'LTC Footer',
     },
    normalLoad: "Normal Load",
    fullLoad: "Full Load",
    page1:{
        image1Url: './images/nokia.png',
        image2Url: './images/we.png',
        table:{
            cell_0_1: ' - ',
            cell_1_1: ' - ',
            cell_2_1: ' - ',
            cell_3_2: ' - ',
            cell_4_2: ' - ',
            cell_5_1: ' - ',
            cell_6_1: ' - ',
            cell_0_3: ' - ',
            cell_1_3: ' - ',
            cell_2_3: ' - ',
            cell_3_5: ' - ',
            cell_4_5: ' - ',
            cell_5_3: ' - ',
            cell_6_3: ' - ',
        }
    },
    page2:{ },
    page3:{ },
    page4:{ },
    page5:{ },
    page6:{ },
    page7:{ },
    page8:{ 
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
        }
    },
    page9:{ 
        sitesListLength: 40,
        sitesList:[
            {
                site: '',
                callId: '',
                band: '',
                longitude: '',
                latitude: '',
                height: '',
                azimuth: '',
                eTilt: '',
                power: '',
                rsBoost: ''
            }
        ]
    },
    page10:{ },
    page11:{ },
    page12:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page13:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page14:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page15:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page16:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page17:{ 
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_9_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
            cell_9_2: '',
        }
    },
    page18:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page19:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page20:{
        image1Url: './images/bg2.jpg',
        image1Error: '',
        image2Url: './images/bg2.jpg',
        image2Error: '',
        table: {
        cell_1_1: '',
        cell_2_1: '',
        cell_3_1: '',
        cell_4_1: '',
        cell_5_1: '',
        cell_6_1: '',
        cell_7_1: '',
        cell_8_1: '',
        cell_1_2: '',
        cell_2_2: '',
        cell_3_2: '',
        cell_4_2: '',
        cell_5_2: '',
        cell_6_2: '',
        cell_7_2: '',
        cell_8_2: '',
        },
     },
    page21:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page22:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page23:{ 
        imageUrl: './images/bg2.jpg',
        table : {
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
        }
    },
    page24:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page25:{ 
        imageUrl: './images/bg2.jpg',
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
        }
    },
    page26:{ 
        imageUrl: './images/bg2.jpg',
    },
    page27:{ 
        imageUrl: './images/bg2.jpg',
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
        }
    },
    page28:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page29:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page30:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page31:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page32:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page33:{ 
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_9_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
            cell_9_2: '',
        }
    },
    page34:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page35:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page36:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
        image2Error:'No Handover Failures Plot',
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
        }
    },
    page37:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page38:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page39:{
        imageUrl: './images/bg2.jpg',
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_9_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
            cell_9_2: '',
        }
     },
    page40:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
     },
    page41:{ 
        imageUrl: './images/bg2.jpg',
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
        }
    },
    page42:{
        imageUrl: './images/bg2.jpg',
     },
    page43:{
        imageUrl: './images/bg2.jpg',
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
        }
     },
    page44:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page45:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page46:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page47:{
        imageUrl: './images/bg2.jpg',
        table:{
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_9_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
            cell_9_2: '',
        }
     },
    page48:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page49:{ 
        image1Url: './images/bg2.jpg',
        image1Error: '',
        image2Url: './images/bg2.jpg',
        image2Error: '',
        table: {
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
            cell_5_1: '',
            cell_6_1: '',
            cell_7_1: '',
            cell_8_1: '',
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',   
        }
    },
    page50:{
        table1:{
            cell_0_1: '',
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
        },
        table2:{
            cell_0_1: '',
            cell_1_1: '',
            cell_2_1: '',
            cell_3_1: '',
            cell_4_1: '',
        }
     },
    page51:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
        image3Url: './images/bg2.jpg',
    },
    page52:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
        image3Url: './images/bg2.jpg',
    },
    page53:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
        image3Url: './images/bg2.jpg',
    },
    page54:{
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
        image3Url: './images/bg2.jpg',
     },
    page55:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
        image3Url: './images/bg2.jpg',
    },
    page56:{ 
        image1Url: './images/bg2.jpg',
        image2Url: './images/bg2.jpg',
    },
    page57:{
        dataLength: 40,
        actions:[
            {
                MRBTS: '',
                LNBTS: '',
                LNCEL: '',
                Action: '',
                ActionDate: ''
            }
        ]

     },
    page58:{ },
    page59:{ 
        table: {
            cell_1_0: '  ',
            cell_2_0: '  ',
            cell_3_0: '  ',
            cell_4_0: '  ',
            cell_5_0: '  ',
            cell_6_0: '  ',
            cell_1_1: '  ',
            cell_2_1: '  ',
            cell_3_1: '  ',
            cell_4_1: '  ',
            cell_5_1: '  ',
            cell_1_2: '  ',
            cell_4_2: '  ',
            cell_5_2: '  ',
            cell_6_2: '  ',
            cell_1_3: '  ',
            cell_2_3: '  ',
            cell_3_3: '  ',
            cell_4_3: '  ',
            cell_5_3: '  ',
            cell_6_3: '  ',
        }
    },
    page60:{ 
        table1:{
            cell_1_2: '',
            cell_2_2: '',
            cell_3_2: '',
            cell_4_2: '',
            cell_5_2: '',
            cell_6_2: '',
            cell_7_2: '',
            cell_8_2: '',
            cell_9_2: '',
            cell_10_2: '',
            cell_1_3: '',
            cell_2_3: '',
            cell_3_3: '',
            cell_4_3: '',
            cell_5_3: '',
            cell_6_3: '',
            cell_7_3: '',
            cell_8_3: '',
            cell_9_3: '',
            cell_10_3: '',
            cell_1_4: '',
            cell_2_4: '',
            cell_3_4: '',
            cell_4_4: '',
            cell_5_4: '',
            cell_6_4: '',
            cell_7_4: '',
            cell_8_4: '',
            cell_9_4: '',
            cell_10_4: '',
        },
        table2:{
            cell_1_3: '',
            cell_2_3: '',
            cell_3_3: '',
            cell_4_3: '',
            cell_5_3: '',
            cell_6_3: '',
            cell_7_3: '',
            cell_8_3: '',
            cell_9_3: '',
            cell_10_3: '',
            cell_11_3: '',
            cell_12_3: '',
            cell_13_3: '',
            cell_14_3: '',
        }
    },
    page61:{
        table1:{
            cell_1_3: '',
            cell_2_3: '',
            cell_3_3: '',
            cell_4_3: '',
            cell_5_3: '',
            cell_6_3: '',
            cell_7_3: '',
            cell_8_3: '',
            cell_9_3: '',
            cell_10_3: '',
            cell_11_3: '',
            cell_12_3: '',
            cell_13_3: '',
            cell_14_3: '',
        },
        table2:{
            cell_1_3: '',
            cell_2_3: '',
            cell_3_3: '',
            cell_4_3: '',
            cell_5_3: '',
            cell_6_3: '',
            cell_7_3: '',
            cell_8_3: '',
            cell_9_3: '',
            cell_10_3: '',
            cell_11_3: '',
            cell_12_3: '',
            cell_13_3: '',
            cell_14_3: '',
        }
     }
}